export const STUDENT_STATUS = {
    INFO: 'INFO',
    CONTACTED: 'CONTACTED',
    ACTIVE: 'ACTIVE',
    PAUSED: 'PAUSED',
    DROPPED_OUT: 'DROPPED_OUT',
    GRADUATED: 'GRADUATED',
};

export const BANK_TRANSACTION_STATUS = {
    PENDING: 'PENDING',
    VERIFIED: 'VERIFIED',
    REJECTED: 'REJECTED',
};

export const DISBURSEMENT_STATUS = {
    HOLDING: 'HOLDING',
    SENT_TO_TEACHER: 'SENT_TO_TEACHER',
    DELIVERED_TO_STUDENT: 'DELIVERED_TO_STUDENT',
};

export const STUDENT_STATUS_TRANSLATIONS = {
    [STUDENT_STATUS.INFO]: 'Đang lấy thông tin',
    [STUDENT_STATUS.CONTACTED]: 'Đã liên hệ',
    [STUDENT_STATUS.ACTIVE]: 'Đang hỗ trợ',
    [STUDENT_STATUS.PAUSED]: 'Tạm dừng',
    [STUDENT_STATUS.DROPPED_OUT]: 'Đã nghỉ học',
    [STUDENT_STATUS.GRADUATED]: 'Đã tốt nghiệp',
};


